CREATE TABLE IF NOT EXISTS movies (
  id TEXT PRIMARY KEY,
  url TEXT,
  primary_title TEXT NOT NULL,
  original_title TEXT,
  type TEXT,
  description TEXT,
  primary_image TEXT,
  thumbnails JSONB,
  trailer TEXT,
  content_rating TEXT,
  start_year INTEGER,
  end_year INTEGER,
  release_date DATE,
  interests JSONB,
  countries_of_origin JSONB,
  external_links JSONB,
  spoken_languages JSONB,
  filming_locations JSONB,
  production_companies JSONB,
  budget NUMERIC,
  gross_worldwide NUMERIC,
  genres JSONB,
  is_adult BOOLEAN,
  runtime_minutes INTEGER,
  average_rating NUMERIC,
  num_votes INTEGER,
  metascore NUMERIC
);